name: Compile & Release

on:
  push:
    branches:
      - master
      - 3.3
      - 3.4

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17
      - name: Upload to Maven
        run: ./gradlew publish
        env:
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}